deb rpm: install missing local plugins during upgrade process
deb:
 * preinst: detect locally installed plugins
   * collect plugin information via fluent-diagtool
 * postinst: install locally installed plugins
   * if network access is denied, giving up install plugins

rpm:
 * %pre $1 == 2 (upgrade): detect locally installed plugins
   * collect plugin information via fluent-diagtool
 * %post $1 == 2 (upgrade): install locally installed plugins
   * if network access is denied, giving up install plugins
Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>

diff --git a/fluent-package/yum/fluent-package.spec.in b/fluent-package/yum/fluent-package.spec.in
--- a/fluent-package/yum/fluent-package.spec.in
+++ b/fluent-package/yum/fluent-package.spec.in
@@ -32,6 +32,8 @@
 %define v4migration_with_restart /tmp/@PACKAGE_DIR@/.v4migration_with_restart
 %define v4migration_old_rotate_config_saved /tmp/@PACKAGE_DIR@/.old_rotate_config
 %define v4migration_enabled_service /tmp/@PACKAGE_DIR@/.v4migration_enabled_service
+%define local_plugin_migration /tmp/@PACKAGE_DIR@/.local_plugin_migration
+%define local_base_plugins /tmp/@PACKAGE_DIR@/.base-plugins
 
 # Omit the brp-python-bytecompile automagic because post hook for ffi fails on AmazonLinux 2.
 %if %{_amazon_ver} == 2
@@ -186,6 +188,25 @@ else
         /usr/sbin/useradd --system --uid $TD_UID --gid $TD_GID --home-dir %{_localstatedir}/lib/@PACKAGE_DIR@ --shell /sbin/nologin --non-unique @SERVICE_NAME@
     fi
 fi
+if [ $1 -eq 2 ]; then
+  # collect manually installed plugins during upgrading
+  archive_path=$(sudo /opt/fluent/bin/fluent-diagtool -t fluentd -o /tmp  | tail -n 1 | cut -d' ' -f10)
+  local_gem_output=$(echo $archive_path | sed -e 's/diagout-//' -e 's/.tar.gz//')/output/gem_local_list.output
+  if [ -f $local_gem_output ]; then
+      if [ -s $local_gem_output ]; then
+	  # If there are missing plugins, mark path to it
+	  echo "Detected missing plugins..."
+	  cp $local_gem_output %{local_plugin_migration}
+      else
+	  echo "Missing $local_gem_output"
+      fi
+  else
+      echo "Missing $local_gem_output to check locally installed plugins."
+  fi
+  rm -f $archive_path
+  archive_dir=$(echo $archive_path | sed -e 's/diagout-//' -e 's/.tar.gz//')
+  rm -rf $archive_dir
+fi
 
 %preun
 %systemd_preun @SERVICE_NAME@.service
@@ -280,6 +301,30 @@ if [ -f "%{_sysconfdir}/prelink.conf" ]; then
   if [ $(grep '\-b /opt/td-agent/bin/ruby' -c %{_sysconfdir}/prelink.conf) -eq 1 ]; then
     echo "Removing prelink settings for td-agent v4 from /etc/prelink.conf ..."
     %{__sed} -i"" %{_sysconfdir}/prelink.conf -e "/\/opt\/td-agent\/bin\/ruby/d"
+  fi
+fi
+if [ $1 -eq 2 ]; then
+  # install missing plugins during upgrading package
+  if [ -f %{local_plugin_migration} ]; then
+    echo "Checking network connectivity..."
+    curl --fail --silent -O https://rubygems.org/specs.4.8.gz
+    if [ $? -eq 0 ]; then
+      echo "Install missing plugins automatically..."
+      /usr/sbin/fluent-gem list | grep fluent-plugin | cut -d' ' -f1 > %{local_base_plugins}
+      # NOTE: Do not install already bundled plugins
+      diff -u %{local_base_plugins} %{local_plugin_migration} | grep '^+fluent' | sed -e 's/\+//' > %{local_missing_plugins}
+      if [ -s %{local_missing_plugins} ]; then
+        cat %{local_missing_plugins} | xargs sudo /usr/sbin/fluent-gem install --no-document
+      else
+         echo "No need to install missing plugins..."
+      fi
+      rm -f %{local_base_plugins}
+      rm -f %{local_missing_plugins}
+    else
+      echo "Can't install missing plugins automatically, please install the following plugins manually."
+      cat %{local_plugin_migration}
+    fi
+    rm -f %{local_plugin_migration}
   fi
 fi
 
