rpm: use mkfifo not to be removed /tmp/td-agent in 10d
On CentOS 6, /usr/sbin/tmpwatch removes regular file,
symlink, and empty directory in 10d.
So to keep it, creates special file such as named pipe.

diff --git a/td-agent/yum/td-agent.spec.in b/td-agent/yum/td-agent.spec.in
--- a/td-agent/yum/td-agent.spec.in
+++ b/td-agent/yum/td-agent.spec.in
@@ -122,12 +122,27 @@ fi
 if [ $1 -eq 0 ]; then
   %{control_service stop @PACKAGE@}
   %{disable_service disable @PACKAGE@}
+  %if ! %{?use_systemd}
+    if [ -p /tmp/@PACKAGE@/.keep ]; then
+        rm -f /tmp/@PACKAGE@/.keep
+    fi
+  %endif
 fi
 
 %post
 if [ $1 -eq 2 ]; then
   %{control_service condrestart @PACKAGE@}
 fi
+%if ! %{?use_systemd}
+  if [ $1 -eq 1 -o $1 -eq 2 ]; then
+    # On CentOS 6, tmpwatch cleanups under /tmp in 10d without
+    # create, access, modify operations. (See /etc/cron.daily/tmpwatch)
+    # To keep it, create special file under /tmp/td-agent.
+    if [ ! -p /tmp/@PACKAGE@/.keep ]; then
+        mkfifo /tmp/@PACKAGE@/.keep
+    fi
+  fi
+%endif
 
 %files
 %defattr(-,root,root,-)
