yum: keep compatibility with older RHEL 9.x (#1087)
When building with latest RHEL 9.x, it breaks ABI compatibility with
older RHEL 9.x because it requires GLIBC_2.35 and OPENSSL_3.4.0.

This is because glibc 2.35 symbols were backported into its glibc 2.34.
It doesn't exist on RHEL 9.6 and earlier version.

Thus build environment should be pinned to 9.2 for keeping compatibility
with all range of RHEL 9.x.

See "Werk #18941: Fix installation failure on AlmaLinux 9 due to
GLIBC_2.35 symbol mismatch"
https://checkmk.com/werk/18941

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>

diff --git a/.github/workflows/_build_rpm_reusable.yml b/.github/workflows/_build_rpm_reusable.yml
--- a/.github/workflows/_build_rpm_reusable.yml
+++ b/.github/workflows/_build_rpm_reusable.yml
@@ -42,6 +42,16 @@ jobs:
         if: ${{ ! steps.cache-rpm.outputs.cache-hit }}
         run: |
           rake yum:build YUM_TARGETS=${{ inputs.rake-job }}
+      - name: Ensure RHEL9 compatibility
+        if: ${{ ! steps.cache-rpm.outputs.cache-hit && startsWith(inputs.rake-job, 'almalinux-9') }}
+        run: |
+          if find fluent-package/yum/repositories -type f -name 'fluent-package-*.rpm' \
+            ! -name '*debug*' ! -name '*.src.rpm' | xargs rpm -qp --requires | grep -qE "GLIBC_2\.(3[6-9]|[4-9][0-9])|OPENSSL_3\.[1-9]"; then
+            echo "::error::Incompatible dependencies (GLIBC_2.36 or later, OPENSSL_3.1.x or later) were detected!"
+            exit 1
+          else
+            echo "Compatibility with GLIBC_ and OPENSSL_ ABI check passed. No incompatible dependencies found."
+          fi
       - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
         if: ${{ ! steps.cache-rpm.outputs.cache-hit && inputs.next-major }}
         with:
